const express = require('express')

const app = express()
const routerList = {
	"msg": "success",
	"menuList": [{
		"menuId": 34,
		"parentId": 0,
		"parentName": null,
		"name": "监控中心",
		"url": null,
		"perms": null,
		"type": 0,
		"icon": "navmonitoring",
		"orderNum": 2,
		"open": null,
		"list": [{
			"menuId": 36,
			"parentId": 34,
			"parentName": null,
			"name": "运输实时监控",
			"url": "monitoring/transport",
			"perms": null,
			'list': [{
				"menuId": 34,
				"parentId": 0,
				"parentName": null,
				"name": "监控中心",
				"url": null,
				"perms": null,
				"type": 0,
				"icon": "navmonitoring",
				"orderNum": 2,
				"open": null,
				"list": [{
					"menuId": 36,
					"parentId": 34,
					"parentName": null,
					"name": "运输实时监控",
					"url": "monitoring/transport",
					"perms": null,

					"type": 1,
					"icon": "",
					"orderNum": 1,
					"open": null,

				}, {
					"menuId": 37,
					"parentId": 34,
					"parentName": null,
					"name": "仓库库存监控",
					"url": "monitoring/warehouse",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 2,
					"open": null,
					"list": null
				}, {
					"menuId": 38,
					"parentId": 34,
					"parentName": null,
					"name": "整车实时看板",
					"url": "monitoring/truckload",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 4,
					"open": null,
					"list": null
				}, {
					"menuId": 39,
					"parentId": 34,
					"parentName": null,
					"name": "运力实时监控",
					"url": "monitoring/full-capacity",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 5,
					"open": null,
					"list": null
				}, {
					"menuId": 40,
					"parentId": 34,
					"parentName": null,
					"name": "异常实时监控",
					"url": "monitoring/exception",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 6,
					"open": null,
					"list": null
				}]
			}, {
				"menuId": 31,
				"parentId": 0,
				"parentName": null,
				"name": "图表分析",
				"url": null,
				"perms": null,
				"type": 0,
				"icon": "nav-caart",
				"orderNum": 3,
				"open": null,
				"list": [{
					"menuId": 32,
					"parentId": 31,
					"parentName": null,
					"name": "运输统计",
					"url": "statistical/transport",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 33,
					"parentId": 31,
					"parentName": null,
					"name": "仓储统计",
					"url": "statistical/warehouse",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 35,
					"parentId": 31,
					"parentName": null,
					"name": "作业指标",
					"url": "statistical/homework",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 41,
					"parentId": 31,
					"parentName": null,
					"name": "线路分析",
					"url": "statistical/lineAnalysis",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 49,
					"parentId": 31,
					"parentName": null,
					"name": "运输安全",
					"url": "statistical/transportsecurity",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 50,
					"parentId": 31,
					"parentName": null,
					"name": "资源利用",
					"url": "statistical/resourcesusing",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 51,
					"parentId": 31,
					"parentName": null,
					"name": "运输数字化",
					"url": "statistical/digital",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}]
			}, {
				"menuId": 54,
				"parentId": 0,
				"parentName": null,
				"name": "数据明细",
				"url": null,
				"perms": null,
				"type": 0,
				"icon": "nav-data",
				"orderNum": 4,
				"open": null,
				"list": [{
					"menuId": 55,
					"parentId": 54,
					"parentName": null,
					"name": "运输明细",
					"url": "detailData/transport-detail",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 56,
					"parentId": 54,
					"parentName": null,
					"name": "仓库信息",
					"url": "detailData/warehouse-info",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 58,
					"parentId": 54,
					"parentName": null,
					"name": "仓库库存变更记录",
					"url": "detailData/warehouse-inv-change",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 59,
					"parentId": 54,
					"parentName": null,
					"name": "仓库出库明细",
					"url": "detailData/warehouse-outbound-detail",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 60,
					"parentId": 54,
					"parentName": null,
					"name": "仓库入库明细",
					"url": "detailData/warehouse-storage-detail",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 61,
					"parentId": 54,
					"parentName": null,
					"name": "库存商品车管理",
					"url": "detailData/inv-commodity-veh-manage",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 62,
					"parentId": 54,
					"parentName": null,
					"name": "异常明细",
					"url": "detailData/abnormal-detail",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 7,
					"open": null,
					"list": null
				}, {
					"menuId": 63,
					"parentId": 54,
					"parentName": null,
					"name": "运输数字化",
					"url": "detailData/digital-detail",
					"perms": null,
					"type": 1,
					"icon": null,
					"orderNum": 8,
					"open": null,
					"list": null
				}]
			}, {
				"menuId": 1,
				"parentId": 0,
				"parentName": null,
				"name": "用户中心",
				"url": null,
				"perms": null,
				"type": 0,
				"icon": "nav-set",
				"orderNum": 5,
				"open": null,
				"list": [{
					"menuId": 57,
					"parentId": 1,
					"parentName": null,
					"name": "组织架构",
					"url": "sys/organizational-structure",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 0,
					"open": null,
					"list": null
				}, {
					"menuId": 2,
					"parentId": 1,
					"parentName": null,
					"name": "用户管理",
					"url": "sys/user",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 1,
					"open": null,
					"list": null
				}, {
					"menuId": 3,
					"parentId": 1,
					"parentName": null,
					"name": "角色管理",
					"url": "sys/role",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 2,
					"open": null,
					"list": null
				}, {
					"menuId": 4,
					"parentId": 1,
					"parentName": null,
					"name": "菜单管理",
					"url": "sys/menu",
					"perms": null,
					"type": 1,
					"icon": "",
					"orderNum": 3,
					"open": null,
					"list": null
				}]
			}],
			"type": 1,
			"icon": "",
			"orderNum": 1,
			"open": null,

		}, {
			"menuId": 37,
			"parentId": 34,
			"parentName": null,
			"name": "仓库库存监控",
			"url": "monitoring/warehouse",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 2,
			"open": null,
			"list": null
		}, {
			"menuId": 38,
			"parentId": 34,
			"parentName": null,
			"name": "整车实时看板",
			"url": "monitoring/truckload",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 4,
			"open": null,
			"list": null
		}, {
			"menuId": 39,
			"parentId": 34,
			"parentName": null,
			"name": "运力实时监控",
			"url": "monitoring/full-capacity",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 5,
			"open": null,
			"list": null
		}, {
			"menuId": 40,
			"parentId": 34,
			"parentName": null,
			"name": "异常实时监控",
			"url": "monitoring/exception",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 6,
			"open": null,
			"list": null
		}]
	}, {
		"menuId": 31,
		"parentId": 0,
		"parentName": null,
		"name": "图表分析",
		"url": null,
		"perms": null,
		"type": 0,
		"icon": "nav-caart",
		"orderNum": 3,
		"open": null,
		"list": [{
			"menuId": 32,
			"parentId": 31,
			"parentName": null,
			"name": "运输统计",
			"url": "statistical/transport",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 33,
			"parentId": 31,
			"parentName": null,
			"name": "仓储统计",
			"url": "statistical/warehouse",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 35,
			"parentId": 31,
			"parentName": null,
			"name": "作业指标",
			"url": "statistical/homework",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 41,
			"parentId": 31,
			"parentName": null,
			"name": "线路分析",
			"url": "statistical/lineAnalysis",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 49,
			"parentId": 31,
			"parentName": null,
			"name": "运输安全",
			"url": "statistical/transportsecurity",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 50,
			"parentId": 31,
			"parentName": null,
			"name": "资源利用",
			"url": "statistical/resourcesusing",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 51,
			"parentId": 31,
			"parentName": null,
			"name": "运输数字化",
			"url": "statistical/digital",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}]
	}, {
		"menuId": 54,
		"parentId": 0,
		"parentName": null,
		"name": "数据明细",
		"url": null,
		"perms": null,
		"type": 0,
		"icon": "nav-data",
		"orderNum": 4,
		"open": null,
		"list": [{
			"menuId": 55,
			"parentId": 54,
			"parentName": null,
			"name": "运输明细",
			"url": "detailData/transport-detail",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 56,
			"parentId": 54,
			"parentName": null,
			"name": "仓库信息",
			"url": "detailData/warehouse-info",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 58,
			"parentId": 54,
			"parentName": null,
			"name": "仓库库存变更记录",
			"url": "detailData/warehouse-inv-change",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 59,
			"parentId": 54,
			"parentName": null,
			"name": "仓库出库明细",
			"url": "detailData/warehouse-outbound-detail",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 60,
			"parentId": 54,
			"parentName": null,
			"name": "仓库入库明细",
			"url": "detailData/warehouse-storage-detail",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 61,
			"parentId": 54,
			"parentName": null,
			"name": "库存商品车管理",
			"url": "detailData/inv-commodity-veh-manage",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 62,
			"parentId": 54,
			"parentName": null,
			"name": "异常明细",
			"url": "detailData/abnormal-detail",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 7,
			"open": null,
			"list": null
		}, {
			"menuId": 63,
			"parentId": 54,
			"parentName": null,
			"name": "运输数字化",
			"url": "detailData/digital-detail",
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNum": 8,
			"open": null,
			"list": null
		}]
	}, {
		"menuId": 1,
		"parentId": 0,
		"parentName": null,
		"name": "用户中心",
		"url": null,
		"perms": null,
		"type": 0,
		"icon": "nav-set",
		"orderNum": 5,
		"open": null,
		"list": [{
			"menuId": 57,
			"parentId": 1,
			"parentName": null,
			"name": "组织架构",
			"url": "sys/organizational-structure",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 0,
			"open": null,
			"list": null
		}, {
			"menuId": 2,
			"parentId": 1,
			"parentName": null,
			"name": "用户管理",
			"url": "sys/user",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 1,
			"open": null,
			"list": null
		}, {
			"menuId": 3,
			"parentId": 1,
			"parentName": null,
			"name": "角色管理",
			"url": "sys/role",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 2,
			"open": null,
			"list": null
		}, {
			"menuId": 4,
			"parentId": 1,
			"parentName": null,
			"name": "菜单管理",
			"url": "sys/menu",
			"perms": null,
			"type": 1,
			"icon": "",
			"orderNum": 3,
			"open": null,
			"list": null
		}]
	}],
	"code": 0,
	"permissions": ["sys:user:list", "sys:menu:update", "sys:menu:delete", "sys:menu:save", "sys:role:save", "sys:role:info", "sys:menu:list", "sys:role:update", "sys:user:info", "sys:user:delete", "sys:role:delete", "sys:user:update", "sys:role:list", "sys:menu:info", "sys:menu:select", "sys:user:save", "sys:role:select"]
}


// const routerList = {
// 	"msg": "success",
// 	"menuList": [
// 		{
// 			"menuId": 34,
// 			"parentId": 0,
// 			"parentName": null,
// 			"name": "监控中心",
// 			"url": null,
// 			"perms": null,
// 			"type": 0,
// 			"icon": "navmonitoring",
// 			"orderNum": 2,
// 			"open": null,
// 			"list": [{
// 				"menuId": 36,
// 				"parentId": 34,
// 				"parentName": null,
// 				"name": "运输实时监控",
// 				"url": "monitoring/transport",
// 				"perms": null,
// 				'list': [{
// 					"menuId": 34,
// 					"parentId": 0,
// 					"parentName": null,
// 					"name": "监控中心",
// 					"url": null,
// 					"perms": null,
// 					"type": 0,
// 					"icon": "navmonitoring",
// 					"orderNum": 2,
// 					"open": null,
// 					"list": [{
// 						"menuId": 36,
// 						"parentId": 34,
// 						"parentName": null,
// 						"name": "运输实时监控",
// 						"url": "monitoring/transport",
// 						"perms": null,

// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 1,
// 						"open": null,

// 					}, {
// 						"menuId": 37,
// 						"parentId": 34,
// 						"parentName": null,
// 						"name": "仓库库存监控",
// 						"url": "monitoring/warehouse",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 2,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 38,
// 						"parentId": 34,
// 						"parentName": null,
// 						"name": "整车实时看板",
// 						"url": "monitoring/truckload",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 4,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 39,
// 						"parentId": 34,
// 						"parentName": null,
// 						"name": "运力实时监控",
// 						"url": "monitoring/full-capacity",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 5,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 40,
// 						"parentId": 34,
// 						"parentName": null,
// 						"name": "异常实时监控",
// 						"url": "monitoring/exception",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 6,
// 						"open": null,
// 						"list": null
// 					}]
// 				}, {
// 					"menuId": 31,
// 					"parentId": 0,
// 					"parentName": null,
// 					"name": "图表分析",
// 					"url": null,
// 					"perms": null,
// 					"type": 0,
// 					"icon": "nav-caart",
// 					"orderNum": 3,
// 					"open": null,
// 					"list": [{
// 						"menuId": 32,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "运输统计",
// 						"url": "statistical/transport",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 33,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "仓储统计",
// 						"url": "statistical/warehouse",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 35,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "作业指标",
// 						"url": "statistical/homework",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 41,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "线路分析",
// 						"url": "statistical/lineAnalysis",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 49,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "运输安全",
// 						"url": "statistical/transportsecurity",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 50,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "资源利用",
// 						"url": "statistical/resourcesusing",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 51,
// 						"parentId": 31,
// 						"parentName": null,
// 						"name": "运输数字化",
// 						"url": "statistical/digital",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}]
// 				}, {
// 					"menuId": 54,
// 					"parentId": 0,
// 					"parentName": null,
// 					"name": "数据明细",
// 					"url": null,
// 					"perms": null,
// 					"type": 0,
// 					"icon": "nav-data",
// 					"orderNum": 4,
// 					"open": null,
// 					"list": [{
// 						"menuId": 55,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "运输明细",
// 						"url": "detailData/transport-detail",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 56,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "仓库信息",
// 						"url": "detailData/warehouse-info",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 58,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "仓库库存变更记录",
// 						"url": "detailData/warehouse-inv-change",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 59,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "仓库出库明细",
// 						"url": "detailData/warehouse-outbound-detail",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 60,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "仓库入库明细",
// 						"url": "detailData/warehouse-storage-detail",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 61,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "库存商品车管理",
// 						"url": "detailData/inv-commodity-veh-manage",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 62,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "异常明细",
// 						"url": "detailData/abnormal-detail",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 7,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 63,
// 						"parentId": 54,
// 						"parentName": null,
// 						"name": "运输数字化",
// 						"url": "detailData/digital-detail",
// 						"perms": null,
// 						"type": 1,
// 						"icon": null,
// 						"orderNum": 8,
// 						"open": null,
// 						"list": null
// 					}]
// 				}, {
// 					"menuId": 1,
// 					"parentId": 0,
// 					"parentName": null,
// 					"name": "用户中心",
// 					"url": null,
// 					"perms": null,
// 					"type": 0,
// 					"icon": "nav-set",
// 					"orderNum": 5,
// 					"open": null,
// 					"list": [{
// 						"menuId": 57,
// 						"parentId": 1,
// 						"parentName": null,
// 						"name": "组织架构",
// 						"url": "sys/organizational-structure",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 0,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 2,
// 						"parentId": 1,
// 						"parentName": null,
// 						"name": "用户管理",
// 						"url": "sys/user",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 1,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 3,
// 						"parentId": 1,
// 						"parentName": null,
// 						"name": "角色管理",
// 						"url": "sys/role",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 2,
// 						"open": null,
// 						"list": null
// 					}, {
// 						"menuId": 4,
// 						"parentId": 1,
// 						"parentName": null,
// 						"name": "菜单管理",
// 						"url": "sys/menu",
// 						"perms": null,
// 						"type": 1,
// 						"icon": "",
// 						"orderNum": 3,
// 						"open": null,
// 						"list": null
// 					}]
// 				}],
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 1,
// 				"open": null,

// 			}, {
// 				"menuId": 37,
// 				"parentId": 34,
// 				"parentName": null,
// 				"name": "仓库库存监控",
// 				"url": "monitoring/warehouse",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 2,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 38,
// 				"parentId": 34,
// 				"parentName": null,
// 				"name": "整车实时看板",
// 				"url": "monitoring/truckload",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 4,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 39,
// 				"parentId": 34,
// 				"parentName": null,
// 				"name": "运力实时监控",
// 				"url": "monitoring/full-capacity",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 5,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 40,
// 				"parentId": 34,
// 				"parentName": null,
// 				"name": "异常实时监控",
// 				"url": "monitoring/exception",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 6,
// 				"open": null,
// 				"list": null
// 			}]
// 		}, {
// 			"menuId": 31,
// 			"parentId": 0,
// 			"parentName": null,
// 			"name": "图表分析",
// 			"url": null,
// 			"perms": null,
// 			"type": 0,
// 			"icon": "nav-caart",
// 			"orderNum": 3,
// 			"open": null,
// 			"list": [{
// 				"menuId": 32,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "运输统计",
// 				"url": "statistical/transport",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 33,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "仓储统计",
// 				"url": "statistical/warehouse",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 35,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "作业指标",
// 				"url": "statistical/homework",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 41,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "线路分析",
// 				"url": "statistical/lineAnalysis",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 49,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "运输安全",
// 				"url": "statistical/transportsecurity",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 50,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "资源利用",
// 				"url": "statistical/resourcesusing",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 51,
// 				"parentId": 31,
// 				"parentName": null,
// 				"name": "运输数字化",
// 				"url": "statistical/digital",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}]
// 		}, {
// 			"menuId": 54,
// 			"parentId": 0,
// 			"parentName": null,
// 			"name": "数据明细",
// 			"url": null,
// 			"perms": null,
// 			"type": 0,
// 			"icon": "nav-data",
// 			"orderNum": 4,
// 			"open": null,
// 			"list": [{
// 				"menuId": 55,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "运输明细",
// 				"url": "detailData/transport-detail",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 56,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "仓库信息",
// 				"url": "detailData/warehouse-info",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 58,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "仓库库存变更记录",
// 				"url": "detailData/warehouse-inv-change",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 59,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "仓库出库明细",
// 				"url": "detailData/warehouse-outbound-detail",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 60,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "仓库入库明细",
// 				"url": "detailData/warehouse-storage-detail",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 61,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "库存商品车管理",
// 				"url": "detailData/inv-commodity-veh-manage",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 62,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "异常明细",
// 				"url": "detailData/abnormal-detail",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 7,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 63,
// 				"parentId": 54,
// 				"parentName": null,
// 				"name": "运输数字化",
// 				"url": "detailData/digital-detail",
// 				"perms": null,
// 				"type": 1,
// 				"icon": null,
// 				"orderNum": 8,
// 				"open": null,
// 				"list": null
// 			}]
// 		}, {
// 			"menuId": 1,
// 			"parentId": 0,
// 			"parentName": null,
// 			"name": "用户中心",
// 			"url": null,
// 			"perms": null,
// 			"type": 0,
// 			"icon": "nav-set",
// 			"orderNum": 5,
// 			"open": null,
// 			"list": [{
// 				"menuId": 57,
// 				"parentId": 1,
// 				"parentName": null,
// 				"name": "组织架构",
// 				"url": "sys/organizational-structure",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 0,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 2,
// 				"parentId": 1,
// 				"parentName": null,
// 				"name": "用户管理",
// 				"url": "sys/user",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 1,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 3,
// 				"parentId": 1,
// 				"parentName": null,
// 				"name": "角色管理",
// 				"url": "sys/role",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 2,
// 				"open": null,
// 				"list": null
// 			}, {
// 				"menuId": 4,
// 				"parentId": 1,
// 				"parentName": null,
// 				"name": "菜单管理",
// 				"url": "sys/menu",
// 				"perms": null,
// 				"type": 1,
// 				"icon": "",
// 				"orderNum": 3,
// 				"open": null,
// 				"list": null
// 			}]
// 		}],
// 	"code": 0,
// 	"permissions": ["sys:user:list", "sys:menu:update", "sys:menu:delete", "sys:menu:save", "sys:role:save", "sys:role:info", "sys:menu:list", "sys:role:update", "sys:user:info", "sys:user:delete", "sys:role:delete", "sys:user:update", "sys:role:list", "sys:menu:info", "sys:menu:select", "sys:user:save", "sys:role:select"]
// }

app.get('/nav', (req, res) => {
	return res.json({ routerList })
})
app.listen(3008, () => {
	console.log('端口一开')
})